[package]
name = "vban"
version = "0.1.0-alpha1"
authors = ["Lily Hopkins <lilopkins@outlook.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/lilopkins/vban-rs"

[dependencies]
byteorder = "1.4.2"
num-traits = "0.2.14"
num-derive = "0.3.3"
